# Generated by Django 5.0.2 on 2024-03-07 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_resettoken_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reset_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
