# Generated by Django 5.0.3 on 2024-03-10 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_address_address_type_alter_address_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
    ]
