# Generated by Django 5.0.3 on 2024-03-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_address_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
