# Generated by Django 5.0.3 on 2024-03-10 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user/default', upload_to='users/%Y/%m'),
        ),
    ]
