# Generated by Django 5.0.2 on 2024-03-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category/default', upload_to='category/%Y/%m'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product/default.png', upload_to='product/%Y/%m'),
        ),
    ]
