# Generated by Django 5.0.3 on 2024-03-09 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_variationname_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='quantity_in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='category/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default=datetime.datetime(2024, 3, 9, 19, 5, 44, 762964), max_length=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variationoption',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
