# Generated by Django 5.0.2 on 2024-03-04 06:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_image_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_date',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category'),
        ),
        migrations.CreateModel(
            name='VariationName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default variation name', max_length=100)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variation_names', to='products.category')),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='VariationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='Default variation option', max_length=100)),
                ('variation_name', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='variation_options', to='products.variationname')),
            ],
            options={
                'unique_together': {('value', 'variation_name')},
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('products', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='products.product')),
                ('variation_options', models.ManyToManyField(related_name='products', to='products.variationoption')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
