# Generated by Django 5.0.3 on 2024-03-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productitem_quantity_in_stock_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category/default', upload_to='category/%Y/%m'),
        ),
    ]
