# Generated by Django 5.0.3 on 2024-03-10 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variationoption',
            old_name='value',
            new_name='option',
        ),
        migrations.AlterUniqueTogether(
            name='variationoption',
            unique_together={('option', 'variation_name')},
        ),
    ]
