# Generated by Django 5.0.2 on 2024-03-04 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='variation_options',
            field=models.ManyToManyField(null=True, related_name='products', to='products.variationoption'),
        ),
        migrations.AlterField(
            model_name='variationoption',
            name='variation_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variation_options', to='products.variationname'),
        ),
    ]
